name: memoria_animales
description: "Juego de memoria con imágenes y sonidos de animales."
publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=3.5.4 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/abeja.png
    - assets/images/gato.png
    - assets/images/leon.png
    - assets/images/perro.png
    - assets/images/pollito.png
    - assets/images/vaca.png
    - assets/images/interrogacion.png 
    - assets/sonidos/abeja.wav
    - assets/sonidos/leon.wav
    - assets/sonidos/perro.wav
    - assets/sonidos/pollito.wav
    - assets/sonidos/vaca.wav
    - assets/sonidos/gato.wav
