name: memoria_animales
description: "Juego de memoria con imágenes y sonidos de animales."
publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=3.5.4 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sonidos/
